# ===========================================================================
# MIGRACIÓN 0001_initial  (generada por: python manage.py makemigrations)
# ---------------------------------------------------------------------------
# Una migración es el "plano" de la estructura de la base de datos. Este
# archivo describe CÓMO crear las 10 tablas de la app semana3.
#
# Al ejecutar `python manage.py migrate`, Django lee este archivo y ejecuta
# los CREATE TABLE correspondientes en db.sqlite3.
#
# NO se edita a mano (estos comentarios son la única excepción, con fines de
# estudio). Si mañana se cambia un modelo, `makemigrations` genera 0002_...
# con SOLO ese cambio (AddField, AlterField, etc.).
#
# CRUD vs migración:
#   - CRUD      cambia FILAS (datos)      -> se hace desde la web con el ORM
#   - migración cambia COLUMNAS/TABLAS    -> se hace con makemigrations + migrate
# ===========================================================================

# Generated by Django 5.2.17 on 2026-09-03 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    # initial=True -> es la PRIMERA migración de la app (crea las tablas desde cero)
    initial = True

    # dependencies -> otras migraciones que deben aplicarse antes.
    # Vacío: esta app no depende de nada (no referencia modelos de otras apps).
    dependencies = [
    ]

    # operations -> la lista de cambios a aplicar, EN ORDEN.
    operations = [
        # -------------------------------------------------------------------
        # CreateModel -> CREATE TABLE. Django ordena las entidades para que
        # una tabla exista antes de que otra la referencie con ForeignKey.
        # Por eso primero van las 5 independientes.
        # -------------------------------------------------------------------

        migrations.CreateModel(
            name='AnioLectivo',
            fields=[
                # 'id': clave primaria automática (entero grande autoincremental).
                # No está escrita en el modelo; Django la agrega sola.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('costo_matricula', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pension', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado')], default='ACTIVO', max_length=10)),
            ],
            options={  # viene del `class Meta` del modelo
                'verbose_name': 'Año lectivo',
                'verbose_name_plural': 'Años lectivos',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_documento', models.CharField(max_length=15, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                # EmailField ocupa max_length=254 por el estándar de emails
                ('correo', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Apoderado',
                'verbose_name_plural': 'Apoderados',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grado', models.CharField(max_length=50)),
                # OJO: el campo 'nivel' (FK) NO se crea aquí. Se agrega más abajo
                # con AddField, porque NivelEducativo aún no existía en este punto.
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'ordering': ['nivel__nombre_nivel', 'nombre_grado'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_metodo', models.CharField(max_length=50, unique=True)),
                ('requiere_voucher', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Método de pago',
                'verbose_name_plural': 'Métodos de pago',
                'ordering': ['nombre_metodo'],
            },
        ),
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_nivel', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Nivel educativo',
                'verbose_name_plural': 'Niveles educativos',
                'ordering': ['nombre_nivel'],
            },
        ),
        migrations.CreateModel(
            name='TipoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de descuento',
                'verbose_name_plural': 'Tipos de descuento',
                'ordering': ['nombre'],
            },
        ),

        # -------------------------------------------------------------------
        # Ahora las entidades RELACIONADas. En cada ForeignKey:
        #   on_delete=PROTECT   -> no deja borrar el padre si tiene hijos
        #   on_delete=CASCADE   -> al borrar el padre, se borran los hijos
        #   on_delete=SET_NULL  -> al borrar el padre, el campo queda en NULL
        #   related_name        -> nombre del "camino de vuelta" (padre.hijos.all())
        #   to='semana3.<modelo>'-> a qué tabla apunta la FK
        # La FK crea físicamente una columna "<campo>_id".
        # -------------------------------------------------------------------

        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_alumno', models.CharField(max_length=20, unique=True)),
                ('num_documento', models.CharField(max_length=15, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('RETIRADO', 'Retirado')], default='ACTIVO', max_length=10)),
                # FK -> Apoderado. PROTECT: no borrar un apoderado con estudiantes.
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='semana3.apoderado')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('costo_matricula', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_matricula', models.CharField(choices=[('VIGENTE', 'Vigente'), ('ANULADA', 'Anulada'), ('TRASLADADA', 'Trasladada')], default='VIGENTE', max_length=12)),
                # 3 ForeignKey, todas PROTECT (conservar historial académico)
                ('anio_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='semana3.aniolectivo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='semana3.estudiante')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='semana3.grado')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['-fecha_registro'],
                # restricción de unicidad sobre la PAREJA de columnas
                'unique_together': {('estudiante', 'anio_lectivo')},
            },
        ),
        # AddField -> ALTER TABLE ADD COLUMN. Agrega 'nivel' a la tabla Grado
        # ahora que NivelEducativo ya existe.
        migrations.AddField(
            model_name='grado',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grados', to='semana3.niveleducativo'),
        ),
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cuota', models.PositiveSmallIntegerField()),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=10)),
                # FK -> Matricula con CASCADE: al borrar la matrícula se borran sus cuotas.
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pensiones', to='semana3.matricula')),
                # FK opcional -> TipoDescuento con SET_NULL (null=True, blank=True):
                # al borrar el descuento, esta columna queda en NULL.
                ('tipo_descuento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pensiones', to='semana3.tipodescuento')),
            ],
            options={
                'verbose_name': 'Pensión',
                'verbose_name_plural': 'Pensiones',
                'ordering': ['matricula', 'num_cuota'],
                'unique_together': {('matricula', 'num_cuota')},
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_operacion', models.DateTimeField()),
                ('num_operacion', models.CharField(max_length=50, unique=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprobante_url', models.URLField(blank=True)),
                ('estado_validacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                # 2 ForeignKey, ambas PROTECT (no perder registros de dinero)
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='semana3.metodopago')),
                ('pension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='semana3.pension')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_operacion'],
            },
        ),
    ]
