# Generated by Django 5.2.17 on 2026-09-03 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnioLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('costo_matricula', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pension', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado')], default='ACTIVO', max_length=10)),
            ],
            options={
                'verbose_name': 'Año lectivo',
                'verbose_name_plural': 'Años lectivos',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_documento', models.CharField(max_length=15, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Apoderado',
                'verbose_name_plural': 'Apoderados',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grado', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'ordering': ['nivel__nombre_nivel', 'nombre_grado'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_metodo', models.CharField(max_length=50, unique=True)),
                ('requiere_voucher', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Método de pago',
                'verbose_name_plural': 'Métodos de pago',
                'ordering': ['nombre_metodo'],
            },
        ),
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_nivel', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Nivel educativo',
                'verbose_name_plural': 'Niveles educativos',
                'ordering': ['nombre_nivel'],
            },
        ),
        migrations.CreateModel(
            name='TipoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de descuento',
                'verbose_name_plural': 'Tipos de descuento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_alumno', models.CharField(max_length=20, unique=True)),
                ('num_documento', models.CharField(max_length=15, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('RETIRADO', 'Retirado')], default='ACTIVO', max_length=10)),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='semana3.apoderado')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('costo_matricula', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_matricula', models.CharField(choices=[('VIGENTE', 'Vigente'), ('ANULADA', 'Anulada'), ('TRASLADADA', 'Trasladada')], default='VIGENTE', max_length=12)),
                ('anio_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='semana3.aniolectivo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='semana3.estudiante')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='semana3.grado')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['-fecha_registro'],
                'unique_together': {('estudiante', 'anio_lectivo')},
            },
        ),
        migrations.AddField(
            model_name='grado',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grados', to='semana3.niveleducativo'),
        ),
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cuota', models.PositiveSmallIntegerField()),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=10)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pensiones', to='semana3.matricula')),
                ('tipo_descuento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pensiones', to='semana3.tipodescuento')),
            ],
            options={
                'verbose_name': 'Pensión',
                'verbose_name_plural': 'Pensiones',
                'ordering': ['matricula', 'num_cuota'],
                'unique_together': {('matricula', 'num_cuota')},
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_operacion', models.DateTimeField()),
                ('num_operacion', models.CharField(max_length=50, unique=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprobante_url', models.URLField(blank=True)),
                ('estado_validacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='semana3.metodopago')),
                ('pension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='semana3.pension')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_operacion'],
            },
        ),
    ]
