# Generated by Django 5.2.17 on 2026-09-09 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semana3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('creditos', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CursoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('estado', models.CharField(choices=[('CURSANDO', 'Cursando'), ('APROBADO', 'Aprobado'), ('DESAPROBADO', 'Desaprobado'), ('RETIRADO', 'Retirado')], default='CURSANDO', max_length=12)),
           ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_curso', to='semana3.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_curso', to='semana3.estudiante')),
            ],
            options={
                'verbose_name': 'Inscripción a curso',
                'verbose_name_plural': 'Inscripciones a cursos',
                'unique_together': {('estudiante', 'curso')},
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='estudiantes', through='semana3.CursoEstudiante', to='semana3.curso'),
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sangre', models.CharField(blank=True, max_length=5)),
                ('alergias', models.TextField(blank=True)),
                ('contacto_emergencia_nombre', models.CharField(max_length=150)),
                ('contacto_emergencia_telefono', models.CharField(max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_medica', to='semana3.estudiante')),
            ],
            options={
                'verbose_name': 'Ficha médica',
                'verbose_name_plural': 'Fichas médicas',
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('ACADEMICA', 'Académica'), ('CONDUCTUAL', 'Conductual'), ('ADMINISTRATIVA', 'Administrativa')], default='ACADEMICA', max_length=15)),
                ('descripcion', models.TextField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='semana3.estudiante')),
            ],
            options={
                'verbose_name': 'Observación',
                'verbose_name_plural': 'Observaciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
