# Generated by Django 6.1 on 2026-10-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semana3', '0002_curso_cursoestudiante_estudiante_cursos_fichamedica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='cupos_disponibles',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
